# Generated by Django 4.1.7 on 2023-03-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("placements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="placement",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
