# Generated by Django 4.1.7 on 2023-03-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("placements", "0002_placement_is_accepted"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed")],
                default="Open",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[("Available", "available"), ("Placed", "placed")],
                default="Available",
                max_length=20,
            ),
        ),
    ]
