name: black-action
on: [push, pull_request]
jobs:
  linter_name:
    name: runner / black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."
      - name: Create Pull Request
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "format code using black - bot"
          commit-message: "format code using black - bot"
          body: |
            There appear to be some python formatting errors in ${{ github.sha }}. This pull request
            applies black formatting and fixes it to main branch.
          base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch
          branch: actions/black
